### ISSUE TITLE
About AQE state

### ISSUE THREAD

**Issue by yunzqq** [tangyoubao/tangyoubao.github.io#1]
I want to consult an issue. For the AQE state, the manuscript will be returned to reviewers?

**Comment by tangyoubao** [comment]
I think it depends on the reviewers' comments. If there is no major concern, the revision should not be sent back to reviewers. The editor will give a decision directly.

**Comment by yunzqq** [comment]
thank you very much for your response.
The comments are raised by two reviewers.&nbsp;&nbsp; The first reviewer gives AQ and the second reviewer gives RQ. The second reviewer request adding an experiment but the experiment is not very reasonable and is influenced by the virus.&nbsp;&nbsp; We can not finish the experiment.&nbsp;&nbsp; At the second round, the first reviewer give AQ again and the the second reviewer still want to see the experiment results(AQ). AE do not mention any about the reviewers's comments.
So i want to consult you (senior fellow apprentice) about this thing.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tangyoubao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上9:46
收件人:&nbsp;"tangyoubao/tangyoubao.github.io"<tangyoubao.github.io@noreply.github.com&gt;;
抄送:&nbsp;"Doctor"<949245661@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tangyoubao/tangyoubao.github.io] About AQE state (#1)





 
I think it depends on the reviewers' comments. If there is no major concern, the revision should not be sent back to reviewers. The editor will give a decision directly.

**Comment by tangyoubao** [comment]
For your case, If the editor ignores the second reviewer's comments, he/she will make the decision. Otherwise, your manuscript will be sent back to the reviewers. I guess. You just need to wait. Your paper should be accepted.

**Comment by yunzqq** [comment]
Thank you (senior fellow apprentice)&nbsp;very much for your response!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tangyoubao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 晚上11:15
收件人:&nbsp;"tangyoubao/tangyoubao.github.io"<tangyoubao.github.io@noreply.github.com&gt;;
抄送:&nbsp;"Doctor"<949245661@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tangyoubao/tangyoubao.github.io] About AQE state (#1)





 
For your case, If the editor ignores the second reviewer's comments, he/she will make the decision. Otherwise, your manuscript will be sent back to the reviewers. I guess. You just need to wait. Your paper should be accepted.
